# Generated by Django 5.0.2 on 2024-02-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Number', models.CharField(max_length=120)),
                ('Room_Rent', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Room_Desc', models.CharField(max_length=255)),
                ('Room_Status', models.CharField(max_length=120)),
                ('Room_City', models.CharField(max_length=255)),
                ('Room_District', models.CharField(max_length=255)),
                ('Square_Feet', models.PositiveIntegerField()),
                ('Room_Image', models.ImageField(upload_to='room_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='tbl_staff',
            old_name='Staff_Pin',
            new_name='Staff_Designation',
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateField()),
                ('Total_price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Booking_Status', models.IntegerField(default=0)),
                ('Cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_customer')),
                ('Room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_room')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=120)),
                ('Card_Name', models.CharField(max_length=120)),
                ('Card_Date', models.CharField(max_length=120)),
                ('Card_Status', models.CharField(max_length=120)),
                ('Card_Cvv', models.CharField(max_length=120)),
                ('Card_Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_customer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=120)),
                ('Cat_Desc', models.CharField(max_length=255)),
                ('Cat_Img', models.ImageField(blank=True, null=True, upload_to='cat_images/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Room_Rating', models.CharField(max_length=120)),
                ('Service_Rating', models.CharField(max_length=120)),
                ('Comment', models.CharField(max_length=255)),
                ('Status', models.IntegerField(default=0)),
                ('Cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_customer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance_name', models.CharField(max_length=120)),
                ('Maintenance_desc', models.CharField(max_length=255)),
                ('Status', models.IntegerField(default=0)),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_staff')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_Phno', models.CharField(max_length=120)),
                ('Owner_Fname', models.CharField(max_length=150)),
                ('Owner_Mname', models.CharField(max_length=150)),
                ('Owner_Lname', models.CharField(max_length=150)),
                ('Owner_Dob', models.CharField(max_length=150)),
                ('Owner_Gender', models.CharField(max_length=150)),
                ('Owner_Dist', models.CharField(max_length=150)),
                ('Owner_City', models.CharField(max_length=150)),
                ('Owner_Pin', models.CharField(max_length=150)),
                ('Owner_Status', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateField()),
                ('Total_price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Status', models.IntegerField(default=0)),
                ('Booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_booking')),
                ('Card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_card')),
                ('Cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_customer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_maintenance_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=120)),
                ('Status', models.IntegerField(default=0)),
                ('Maintenance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_maintenance')),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_staff')),
                ('Room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_room')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcat_Name', models.CharField(max_length=120)),
                ('Subcat_Desc', models.CharField(max_length=255)),
                ('Subcat_Img', models.ImageField(blank=True, null=True, upload_to='subcat_images/')),
                ('Cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_category')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_room',
            name='Subcat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_subcategory'),
        ),
    ]
