# Generated by Django 5.0.2 on 2024-02-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_rental', '0002_tbl_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_category',
            name='username',
        ),
    ]
