# Generated by Django 5.0.2 on 2024-02-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_rental', '0003_remove_tbl_category_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_payment',
            name='Booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_card',
            name='Card_Cust',
        ),
        migrations.RemoveField(
            model_name='tbl_payment',
            name='Card_id',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tbl_payment',
            name='Cust_id',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='Cust_id',
        ),
        migrations.RemoveField(
            model_name='tbl_owner',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tbl_staff',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tbl_maintenance',
            name='Staff_id',
        ),
        migrations.RemoveField(
            model_name='tbl_maintenance_assign',
            name='Maintenance_id',
        ),
        migrations.RemoveField(
            model_name='tbl_maintenance_assign',
            name='Room_id',
        ),
        migrations.RemoveField(
            model_name='tbl_maintenance_assign',
            name='Staff_id',
        ),
        migrations.RemoveField(
            model_name='tbl_room',
            name='Subcat_id',
        ),
        migrations.AlterField(
            model_name='tbl_subcategory',
            name='Cat_id',
            field=models.ForeignKey(db_column='Cat_id', on_delete=django.db.models.deletion.CASCADE, to='apartment_rental.tbl_category'),
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_card',
        ),
        migrations.DeleteModel(
            name='tbl_payment',
        ),
        migrations.DeleteModel(
            name='tbl_customer',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_owner',
        ),
        migrations.DeleteModel(
            name='tbl_login',
        ),
        migrations.DeleteModel(
            name='tbl_maintenance',
        ),
        migrations.DeleteModel(
            name='tbl_maintenance_assign',
        ),
        migrations.DeleteModel(
            name='tbl_Staff',
        ),
        migrations.DeleteModel(
            name='tbl_room',
        ),
    ]
